"""Native names for tesseract language codes.

Used by both the desktop GUI (``gui.py``) and the web app (``app.py``)
to render the OCR language picker with human-friendly labels instead
of the raw tesseract codes (`eng`, `slk`, `chi_sim`, …).

Codes that aren't in this map (e.g. custom training data like ``snum``)
fall back to displaying the code itself.
"""
from __future__ import annotations

TESSERACT_LANG_NAMES: dict[str, str] = {
    "afr": "Afrikaans",
    "amh": "አማርኛ",
    "ara": "العربية",
    "asm": "অসমীয়া",
    "aze": "Azərbaycanca",
    "aze_cyrl": "Азәрбајҹан",
    "bel": "Беларуская",
    "ben": "বাংলা",
    "bod": "བོད་ཡིག",
    "bos": "Bosanski",
    "bre": "Brezhoneg",
    "bul": "Български",
    "cat": "Català",
    "ceb": "Cebuano",
    "ces": "Čeština",
    "chi_sim": "中文 (简体)",
    "chi_sim_vert": "中文 (简体, 竖排)",
    "chi_tra": "中文 (繁體)",
    "chi_tra_vert": "中文 (繁體, 直排)",
    "chr": "ᏣᎳᎩ",
    "cos": "Corsu",
    "cym": "Cymraeg",
    "dan": "Dansk",
    "deu": "Deutsch",
    "div": "ދިވެހި",
    "dzo": "རྫོང་ཁ",
    "ell": "Ελληνικά",
    "eng": "English",
    "enm": "Middle English",
    "epo": "Esperanto",
    "equ": "Math / Equation",
    "est": "Eesti",
    "eus": "Euskara",
    "fao": "Føroyskt",
    "fas": "فارسی",
    "fil": "Filipino",
    "fin": "Suomi",
    "fra": "Français",
    "frk": "Fraktur",
    "frm": "Moyen Français",
    "fry": "Frysk",
    "gla": "Gàidhlig",
    "gle": "Gaeilge",
    "glg": "Galego",
    "grc": "Ἑλληνική",
    "guj": "ગુજરાતી",
    "hat": "Kreyòl Ayisyen",
    "heb": "עברית",
    "hin": "हिन्दी",
    "hrv": "Hrvatski",
    "hun": "Magyar",
    "hye": "Հայերեն",
    "iku": "ᐃᓄᒃᑎᑐᑦ",
    "ind": "Bahasa Indonesia",
    "isl": "Íslenska",
    "ita": "Italiano",
    "ita_old": "Italiano (Old)",
    "jav": "Basa Jawa",
    "jpn": "日本語",
    "jpn_vert": "日本語 (縦書き)",
    "kan": "ಕನ್ನಡ",
    "kat": "ქართული",
    "kat_old": "ქართული (Old)",
    "kaz": "Қазақша",
    "khm": "ខ្មែរ",
    "kir": "Кыргызча",
    "kmr": "Kurdî",
    "kor": "한국어",
    "kor_vert": "한국어 (세로)",
    "lao": "ລາວ",
    "lat": "Latina",
    "lav": "Latviešu",
    "lit": "Lietuvių",
    "ltz": "Lëtzebuergesch",
    "mal": "മലയാളം",
    "mar": "मराठी",
    "mkd": "Македонски",
    "mlt": "Malti",
    "mon": "Монгол",
    "mri": "Māori",
    "msa": "Bahasa Melayu",
    "mya": "မြန်မာ",
    "nep": "नेपाली",
    "nld": "Nederlands",
    "nor": "Norsk",
    "oci": "Occitan",
    "ori": "ଓଡ଼ିଆ",
    "pan": "ਪੰਜਾਬੀ",
    "pol": "Polski",
    "por": "Português",
    "pus": "پښتو",
    "que": "Runa Simi",
    "ron": "Română",
    "rus": "Русский",
    "san": "संस्कृतम्",
    "sin": "සිංහල",
    "slk": "Slovenčina",
    "slv": "Slovenščina",
    "snd": "سنڌي",
    "spa": "Español",
    "spa_old": "Español (Old)",
    "sqi": "Shqip",
    "srp": "Српски",
    "srp_latn": "Srpski (latinica)",
    "sun": "Basa Sunda",
    "swa": "Kiswahili",
    "swe": "Svenska",
    "syr": "ܠܫܢܐ ܣܘܪܝܝܐ",
    "tam": "தமிழ்",
    "tat": "Татарча",
    "tel": "తెలుగు",
    "tgk": "Тоҷикӣ",
    "tha": "ไทย",
    "tir": "ትግርኛ",
    "ton": "Lea Faka-Tonga",
    "tur": "Türkçe",
    "uig": "ئۇيغۇرچە",
    "ukr": "Українська",
    "urd": "اردو",
    "uzb": "Oʻzbekcha",
    "uzb_cyrl": "Ўзбекча (кирилл)",
    "vie": "Tiếng Việt",
    "yid": "ייִדיש",
    "yor": "Yorùbá",
}


def pretty(code: str) -> str:
    """Return the human-friendly name for a tesseract code, falling
    back to the code itself if unknown."""
    return TESSERACT_LANG_NAMES.get(code, code)
